# Generated by Django 4.1.7 on 2023-03-21 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApiApp', '0003_alter_blog_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
