# Generated by Django 4.1.7 on 2023-03-21 22:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('BlogApiApp', '0004_blog_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='reactor',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
