# Generated by Django 4.1.7 on 2023-03-22 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BlogApiApp', '0005_blog_reactor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(null=True)),
            ],
        ),
    ]
